/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface AppSidebar {
        "isOpen": boolean;
        "logo": string;
        "position": 'left' | 'right';
        "showDropdownButton": boolean;
        "width": string;
    }
    interface JbpmAppSidebar {
        "activeNav": string;
        "navItems": any;
        "sidebarSlogan": string;
        "sidebarTitle": string;
    }
    interface JbpmDashboard {
    }
    interface JbpmLogin {
        "bgImg": string;
        "forgetPasswrdText": string;
        "formDescription": string;
        "formTitle": string;
        "password": string;
        "passwordLabel": string;
        "passwordPlaceholder": string;
        "submitBtnText": string;
        "userLabel": string;
        "userPlaceholder": string;
        "username": string;
    }
    interface JbpmLoginTest {
        "password": string;
        "username": string;
    }
    interface MyComponent {
        /**
          * The first name
         */
        "first": string;
        /**
          * The last name
         */
        "last": string;
        /**
          * The middle name
         */
        "middle": string;
    }
}
export interface JbpmLoginCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLJbpmLoginElement;
}
export interface JbpmLoginTestCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLJbpmLoginTestElement;
}
declare global {
    interface HTMLAppSidebarElement extends Components.AppSidebar, HTMLStencilElement {
    }
    var HTMLAppSidebarElement: {
        prototype: HTMLAppSidebarElement;
        new (): HTMLAppSidebarElement;
    };
    interface HTMLJbpmAppSidebarElement extends Components.JbpmAppSidebar, HTMLStencilElement {
    }
    var HTMLJbpmAppSidebarElement: {
        prototype: HTMLJbpmAppSidebarElement;
        new (): HTMLJbpmAppSidebarElement;
    };
    interface HTMLJbpmDashboardElement extends Components.JbpmDashboard, HTMLStencilElement {
    }
    var HTMLJbpmDashboardElement: {
        prototype: HTMLJbpmDashboardElement;
        new (): HTMLJbpmDashboardElement;
    };
    interface HTMLJbpmLoginElementEventMap {
        "signSubmited": any;
    }
    interface HTMLJbpmLoginElement extends Components.JbpmLogin, HTMLStencilElement {
        addEventListener<K extends keyof HTMLJbpmLoginElementEventMap>(type: K, listener: (this: HTMLJbpmLoginElement, ev: JbpmLoginCustomEvent<HTMLJbpmLoginElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLJbpmLoginElementEventMap>(type: K, listener: (this: HTMLJbpmLoginElement, ev: JbpmLoginCustomEvent<HTMLJbpmLoginElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLJbpmLoginElement: {
        prototype: HTMLJbpmLoginElement;
        new (): HTMLJbpmLoginElement;
    };
    interface HTMLJbpmLoginTestElementEventMap {
        "signSubmited": any;
    }
    interface HTMLJbpmLoginTestElement extends Components.JbpmLoginTest, HTMLStencilElement {
        addEventListener<K extends keyof HTMLJbpmLoginTestElementEventMap>(type: K, listener: (this: HTMLJbpmLoginTestElement, ev: JbpmLoginTestCustomEvent<HTMLJbpmLoginTestElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLJbpmLoginTestElementEventMap>(type: K, listener: (this: HTMLJbpmLoginTestElement, ev: JbpmLoginTestCustomEvent<HTMLJbpmLoginTestElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLJbpmLoginTestElement: {
        prototype: HTMLJbpmLoginTestElement;
        new (): HTMLJbpmLoginTestElement;
    };
    interface HTMLMyComponentElement extends Components.MyComponent, HTMLStencilElement {
    }
    var HTMLMyComponentElement: {
        prototype: HTMLMyComponentElement;
        new (): HTMLMyComponentElement;
    };
    interface HTMLElementTagNameMap {
        "app-sidebar": HTMLAppSidebarElement;
        "jbpm-app-sidebar": HTMLJbpmAppSidebarElement;
        "jbpm-dashboard": HTMLJbpmDashboardElement;
        "jbpm-login": HTMLJbpmLoginElement;
        "jbpm-login-test": HTMLJbpmLoginTestElement;
        "my-component": HTMLMyComponentElement;
    }
}
declare namespace LocalJSX {
    interface AppSidebar {
        "isOpen"?: boolean;
        "logo"?: string;
        "position"?: 'left' | 'right';
        "showDropdownButton"?: boolean;
        "width"?: string;
    }
    interface JbpmAppSidebar {
        "activeNav"?: string;
        "navItems"?: any;
        "sidebarSlogan"?: string;
        "sidebarTitle"?: string;
    }
    interface JbpmDashboard {
    }
    interface JbpmLogin {
        "bgImg"?: string;
        "forgetPasswrdText"?: string;
        "formDescription"?: string;
        "formTitle"?: string;
        "onSignSubmited"?: (event: JbpmLoginCustomEvent<any>) => void;
        "password"?: string;
        "passwordLabel"?: string;
        "passwordPlaceholder"?: string;
        "submitBtnText"?: string;
        "userLabel"?: string;
        "userPlaceholder"?: string;
        "username"?: string;
    }
    interface JbpmLoginTest {
        "onSignSubmited"?: (event: JbpmLoginTestCustomEvent<any>) => void;
        "password"?: string;
        "username"?: string;
    }
    interface MyComponent {
        /**
          * The first name
         */
        "first"?: string;
        /**
          * The last name
         */
        "last"?: string;
        /**
          * The middle name
         */
        "middle"?: string;
    }
    interface IntrinsicElements {
        "app-sidebar": AppSidebar;
        "jbpm-app-sidebar": JbpmAppSidebar;
        "jbpm-dashboard": JbpmDashboard;
        "jbpm-login": JbpmLogin;
        "jbpm-login-test": JbpmLoginTest;
        "my-component": MyComponent;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "app-sidebar": LocalJSX.AppSidebar & JSXBase.HTMLAttributes<HTMLAppSidebarElement>;
            "jbpm-app-sidebar": LocalJSX.JbpmAppSidebar & JSXBase.HTMLAttributes<HTMLJbpmAppSidebarElement>;
            "jbpm-dashboard": LocalJSX.JbpmDashboard & JSXBase.HTMLAttributes<HTMLJbpmDashboardElement>;
            "jbpm-login": LocalJSX.JbpmLogin & JSXBase.HTMLAttributes<HTMLJbpmLoginElement>;
            "jbpm-login-test": LocalJSX.JbpmLoginTest & JSXBase.HTMLAttributes<HTMLJbpmLoginTestElement>;
            "my-component": LocalJSX.MyComponent & JSXBase.HTMLAttributes<HTMLMyComponentElement>;
        }
    }
}
